/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CODIGOS;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mael
 */
public class Teste_Xadrez extends javax.swing.JFrame {
    
private Image IMAGEM_DE_FUNDO;
String Imagem_de_Fundo = "res\\QUADRADO_1.jpg";//Ghost_1.gif /// QUADRADO_1.jpg
String Imagem_de_Fundo_2 = "res\\QUADRADO_2.jpg";
ImageIcon referencia = new ImageIcon(Imagem_de_Fundo);
ImageIcon referencia_2 = new ImageIcon(Imagem_de_Fundo_2);
public int X = 8;
public int Y = 31;

    /**
     * Creates new form Teste
     */
    public Teste_Xadrez() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LABEL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(456, 479));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(LABEL)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LABEL)
                .addGap(0, 300, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /*
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    */
    public void formMouseClicked(java.awt.event.MouseEvent evt){
        
        
        
        LABEL.setText(""+evt.getX());
        
        //LABEL.setLocation(evt.getX(), evt.getY());
                
        String texto = LABEL.getText();
        
        if(texto.equals("")){
            this.X = 26;
        }
        
        else 
        if(!texto.equals(""))
        {
            this.X = Integer.parseInt(texto);
        }
        
        
          
    }//GEN-LAST:event_formMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Graphics g = null;
        
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
            .addKeyEventDispatcher(new KeyEventDispatcher() {
                @Override
                public boolean dispatchKeyEvent(KeyEvent event) {
                    if(event.getID() == KeyEvent.KEY_RELEASED 
                       && event.getKeyCode() == KeyEvent.VK_UP){
                        
                        
                        
                        LABEL.setText("CIMA");
                        
                           return true;
                     }
                    else
                        if(event.getID() == KeyEvent.KEY_RELEASED 
                       && event.getKeyCode() == KeyEvent.VK_F1){
                        /*MENU_SOBRE obj = new MENU_SOBRE();
                        JanelaInternaPrincipal.add(obj);
                        obj.setVisible(true);*/
                           return true;
                     }
                    else
                        if(event.getID() == KeyEvent.KEY_RELEASED 
                       && event.getKeyCode() == KeyEvent.VK_F3){
                        /*TELA_DO_GRAFICO obj = new TELA_DO_GRAFICO();
                        JanelaInternaPrincipal.add(obj);
                        obj.setVisible(true);*/
                           return true;
                     }
                     return false;
                }
        });
        
    }//GEN-LAST:event_formWindowOpened

    public void paint(Graphics g){
        
        
        
        Graphics2D graficos = (Graphics2D) g;
        
        int TAMANHO = 450;
        
        graficos.setColor(Color.WHITE);
        for(int HORIZONTAL = 3; HORIZONTAL <= TAMANHO; HORIZONTAL += 100){
            for(int VERTICAL = 26; VERTICAL <= TAMANHO; VERTICAL +=100){
                IMAGEM_DE_FUNDO = referencia.getImage();
                graficos.drawImage(IMAGEM_DE_FUNDO, HORIZONTAL, VERTICAL, null);
            }
        }
        graficos.setColor(Color.WHITE);
        for(int HORIZONTAL = 53; HORIZONTAL <= TAMANHO; HORIZONTAL += 100){
            for(int VERTICAL = 76; VERTICAL <= TAMANHO; VERTICAL +=100){
                //g.fillRect(HORIZONTAL, VERTICAL, 50, 50);
                IMAGEM_DE_FUNDO = referencia.getImage();
                graficos.drawImage(IMAGEM_DE_FUNDO, HORIZONTAL, VERTICAL, null);
            }
        }
        graficos.setColor(Color.BLACK);
        for(int HORIZONTAL = 53; HORIZONTAL <= TAMANHO; HORIZONTAL += 100){
            for(int VERTICAL = 26; VERTICAL <= TAMANHO; VERTICAL +=100){
                //g.fillRect(HORIZONTAL, VERTICAL, 50, 50);
                IMAGEM_DE_FUNDO = referencia_2.getImage();
                graficos.drawImage(IMAGEM_DE_FUNDO, HORIZONTAL, VERTICAL, null);
            }
        }
        graficos.setColor(Color.BLACK);
        for(int HORIZONTAL = 3; HORIZONTAL <= TAMANHO; HORIZONTAL += 100){
            for(int VERTICAL = 76; VERTICAL <= TAMANHO; VERTICAL +=100){
                //g.fillRect(HORIZONTAL, VERTICAL, 50, 50);
                IMAGEM_DE_FUNDO = referencia_2.getImage();
                graficos.drawImage(IMAGEM_DE_FUNDO, HORIZONTAL, VERTICAL, null);
            }
        }
        
        //////////////////////// PEÕES AMARELOS //////////////////////////////////
        
        g.setColor(Color.YELLOW);
        for(int HORIZONTAL = 58; HORIZONTAL <= TAMANHO+50; HORIZONTAL += 100){
            for(int VERTICAL = 31; VERTICAL <= TAMANHO-250; VERTICAL +=100){
                g.fillOval(HORIZONTAL, VERTICAL, 40, 40);
            }
        }
        g.setColor(Color.YELLOW);
        for(int HORIZONTAL = 8; HORIZONTAL <= TAMANHO+50; HORIZONTAL += 100){
            for(int VERTICAL = 81; VERTICAL <= TAMANHO-250; VERTICAL +=100){
                g.fillOval(HORIZONTAL, VERTICAL, 40, 40);
            }
        }
        
        //////////////////////// PEÕES VERMELHOS //////////////////////////////////
        
        g.setColor(Color.RED);
        for(int HORIZONTAL = 58; HORIZONTAL <= TAMANHO+50; HORIZONTAL += 100){
            for(int VERTICAL = 331; VERTICAL <= TAMANHO; VERTICAL +=100){
                g.fillOval(HORIZONTAL, VERTICAL, 40, 40);
            }
        }
        g.setColor(Color.RED);
        for(int HORIZONTAL = 8; HORIZONTAL <= TAMANHO+50; HORIZONTAL += 100){
            for(int VERTICAL = 381; VERTICAL <= TAMANHO+50; VERTICAL +=100){
                g.fillOval(HORIZONTAL, VERTICAL, 40, 40);
            }
        }
        
        
        g.setColor(Color.BLACK);
        g.fillOval(this.X, this.Y, 40, 40);
        
        
        //graficos.drawString("Teste: ", 3, 18);
        
        graficos.dispose();
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teste_Xadrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teste_Xadrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teste_Xadrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teste_Xadrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teste_Xadrez().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LABEL;
    // End of variables declaration//GEN-END:variables
}